### ISSUE TITLE
Untag

### ISSUE THREAD

**Issue by karl-friman** [RohitKotiveetil/UnrealEngine--Binoculars#1]
What update would you do to clear the tag of an object once it's set, the second time the player right clicks that object? From BPC_TagWidget -> onTagged branch "true" what would the next steps be to disable and clear that tag?

Another question: The "for each"-loop is set to always trigger now under "Tag Target Entity" in BP_Binoculars (even when "is not valid") is this correct?

**Comment by RohitKotiveetil** [comment]
Hey, thanks for pointing it out. I had not really think about the untagging part of the system. But it won't require a lot of changes.

Basically, after onTagged branch "true", add the following operations:
1. Set Component Tick Enabled = False (we don't want it having any impact on the tick performance)
2. Clear & Invalidate the timer (create a timer handle variable during set timer operation so that you can use it to clear the timer)
3. Get User Widget Object and call Set Visibility on it with visibility set to Hidden.

I'll also add the same changes to the GitHub version sometime before the weekend.

As for the for each loop, yes you can add an "Is Valid" check to make it safer. Plus use the 'Get Render Custom Depth' operation from the for each loop and then use a NOT operation on it before passing it to "Set Custom Render Depth". This will ensure that it will flip between on/off states each time.

**Comment by karl-friman** [comment]
Hi thank you I wasn't able to work it out myself though :( I got stuck at "create a timer handle variable during set timer operation so that you can use it to clear the timer", couldn't work it out) Still wishing for that update!

**Comment by RohitKotiveetil** [comment]
Hi, I was busy with work last week. So couldn't get around to working on it.

I've committed a new build with support for untagging (only in Binoculars mode) tagged actors. You can check out the implementation in BPC_TagWidget.

**Comment by karl-friman** [comment]
Wow thank you. I really like the way you're building these, I learn a lot from looking at it.

**Comment by RohitKotiveetil** [comment]
I'm really glad to hear that. :) Anytime you have any suggestions or doubts like these, feel free to contact me. I'd love to hear what can be done to improve these projects.
